import 'package:force_vive/models/exercise.dart';
import 'package:force_vive/models/workout.dart';
import 'package:force_vive/models/achievement.dart';

class SampleData {
  static final List<Exercise> exercises = [
    Exercise(
      id: 'push_ups',
      name: 'Pompes',
      description: 'Exercice classique pour développer les pectoraux, triceps et deltoïdes',
      muscleGroups: ['chest', 'triceps', 'shoulders'],
      equipment: 'bodyweight',
      difficulty: 'beginner',
      instructions: '1. Position planche, bras tendus\n2. Descendez en contrôlant\n3. Remontez en poussant fort\n4. Gardez le corps droit',
      imageUrl: 'https://pixabay.com/get/gf75d6c80607603532d9b8cb0509a42899ae4aa4842f470b65a75641d98a019a7140d595a8d14230f9cdf9c6fdd7f6cce8d41995207c4fd527b7ff605e60dec84_1280.jpg',
      isCompound: true,
      estimatedDurationSeconds: 60,
    ),
    Exercise(
      id: 'squats',
      name: 'Squats',
      description: 'L\'exercice roi pour les jambes et les fessiers',
      muscleGroups: ['legs', 'glutes'],
      equipment: 'bodyweight',
      difficulty: 'beginner',
      instructions: '1. Pieds écartés largeur d\'épaules\n2. Descendez comme pour s\'asseoir\n3. Remontez en poussant sur les talons\n4. Gardez le dos droit',
      imageUrl: 'https://pixabay.com/get/gcaebd4b254955662dc9f78d00b9e42158990954d06d977d03327d8b7dd2dd237736d4b943efcfc95e60f5a47f0d04fbaaa427679d14ddf8dbdcd3e4f28899045_1280.jpg',
      isCompound: true,
      estimatedDurationSeconds: 60,
    ),
    Exercise(
      id: 'pull_ups',
      name: 'Tractions',
      description: 'Excellent pour développer le dos et les biceps',
      muscleGroups: ['back', 'biceps'],
      equipment: 'pull_up_bar',
      difficulty: 'intermediate',
      instructions: '1. Suspendez-vous à la barre\n2. Tirez jusqu\'au menton\n3. Descendez contrôlé\n4. Bras complètement tendus en bas',
      imageUrl: 'https://pixabay.com/get/gf431bb147f7860be0aa4663643f10f17ef7fccef50ced70b7a9acfb820c3af0cd0726e7cbc15de36d196815a2856b1b0e7b759bfd545ec0a395b543f73a3955b_1280.jpg',
      isCompound: true,
      estimatedDurationSeconds: 45,
    ),
    Exercise(
      id: 'plank',
      name: 'Gainage',
      description: 'Renforcez votre sangle abdominale et votre stabilité',
      muscleGroups: ['core'],
      equipment: 'bodyweight',
      difficulty: 'beginner',
      instructions: '1. Position pompe, sur les avant-bras\n2. Corps droit comme une planche\n3. Contractez les abdos\n4. Respirez normalement',
      imageUrl: 'https://pixabay.com/get/gc4729c425269539fe9efc373db7b5a600aa53a15754311bb4dbeee36036a32aee94c87d60b58ae0dcf00a1504c857068de1c49220dc252402b708d7b0f95d0d3_1280.jpg',
      isCompound: false,
      estimatedDurationSeconds: 90,
    ),
    Exercise(
      id: 'lunges',
      name: 'Fentes',
      description: 'Travaillez jambes et équilibre avec cet exercice unilatéral',
      muscleGroups: ['legs', 'glutes'],
      equipment: 'bodyweight',
      difficulty: 'beginner',
      instructions: '1. Pas en avant, jambe arrière à 90°\n2. Descendez le genou vers le sol\n3. Remontez sur la jambe avant\n4. Alternez les jambes',
      imageUrl: 'https://pixabay.com/get/gf906fb18859f05bf22411e392e58b02f46ba2009e338a7f5ee8a9f0e2b9bf0a2fd55968ad55c9fba4397c59570ddfb21bd0727b90b03bb2b3fbdaa7920cc6623_1280.jpg',
      isCompound: true,
      estimatedDurationSeconds: 60,
    ),
    Exercise(
      id: 'deadlift',
      name: 'Soulevé de terre',
      description: 'L\'exercice le plus complet pour la chaîne postérieure',
      muscleGroups: ['back', 'legs', 'glutes'],
      equipment: 'barbell',
      difficulty: 'intermediate',
      instructions: '1. Barre au sol, pieds sous la barre\n2. Saisissez la barre, dos droit\n3. Soulevez en poussant les hanches\n4. Redescendez contrôlé',
      imageUrl: 'https://pixabay.com/get/g18e12e6dec5b988c17c902e22da23b8cdd4e055c6986390357b468f91b0dd8591b0a0e9e07be787beb3458ce68849cb5c9886fddad52f46cd2d3e06dbac6ffcd_1280.jpg',
      isCompound: true,
      estimatedDurationSeconds: 90,
    ),
    Exercise(
      id: 'bench_press',
      name: 'Développé couché',
      description: 'L\'exercice de référence pour les pectoraux',
      muscleGroups: ['chest', 'triceps', 'shoulders'],
      equipment: 'barbell',
      difficulty: 'intermediate',
      instructions: '1. Allongé sur le banc, barre au-dessus\n2. Descendez contrôlé à la poitrine\n3. Poussez fort vers le haut\n4. Bras complètement tendus',
      imageUrl: 'https://pixabay.com/get/gd1b97d4c56313fde78e46900802add1d11848eafb79a15fb62ea84ab0480bb64d2c3e6caa5869a8b034a37d4e601684150d9ddec58f4529463048be81c742a0c_1280.jpg',
      isCompound: true,
      estimatedDurationSeconds: 75,
    ),
    Exercise(
      id: 'burpees',
      name: 'Burpees',
      description: 'Exercice cardio ultra-intense pour tout le corps',
      muscleGroups: ['full_body'],
      equipment: 'bodyweight',
      difficulty: 'advanced',
      instructions: '1. Debout, descendez en squat\n2. Sautez en position pompe\n3. Faites une pompe\n4. Sautez et levez les bras',
      imageUrl: 'https://pixabay.com/get/gbe1ddb5c6a8b77f859cc2ea62cda6378b1b9e0c82322c9b9e21ba66e30c4b0234cc59637de6923d36531674296c15f547e8548416107683b1b5bbc95f6a8d5fe_1280.jpg',
      isCompound: true,
      estimatedDurationSeconds: 45,
    ),
  ];

  static final List<Achievement> achievements = [
    Achievement(
      id: 'first_workout',
      name: 'Premier Pas',
      description: 'Complétez votre première séance',
      iconName: 'star',
      category: 'workout',
      targetValue: 1,
      unit: 'séance',
    ),
    Achievement(
      id: 'consistent_week',
      name: 'Semaine Parfaite',
      description: '7 jours d\'entraînement consécutifs',
      iconName: 'local_fire_department',
      category: 'consistency',
      targetValue: 7,
      unit: 'jours',
    ),
    Achievement(
      id: 'strength_milestone',
      name: 'Force Brute',
      description: 'Soulevez 1000kg au total',
      iconName: 'fitness_center',
      category: 'strength',
      targetValue: 1000,
      unit: 'kg',
    ),
    Achievement(
      id: 'workout_veteran',
      name: 'Vétéran',
      description: '50 séances complétées',
      iconName: 'military_tech',
      category: 'workout',
      targetValue: 50,
      unit: 'séances',
    ),
    Achievement(
      id: 'hundred_sets',
      name: 'Centurion',
      description: '100 séries réalisées',
      iconName: 'emoji_events',
      category: 'milestone',
      targetValue: 100,
      unit: 'séries',
    ),
    Achievement(
      id: 'consistency_master',
      name: 'Maître de la Régularité',
      description: '30 jours d\'entraînement consécutifs',
      iconName: 'schedule',
      category: 'consistency',
      targetValue: 30,
      unit: 'jours',
    ),
  ];

  static final List<Workout> sampleWorkouts = [
    Workout(
      id: 'beginner_full_body',
      name: 'Corps Complet Débutant',
      description: 'Programme parfait pour commencer la musculation',
      exercises: [
        WorkoutExercise(
          exercise: exercises.firstWhere((e) => e.id == 'push_ups'),
          sets: [
            ExerciseSet(reps: 8, weight: 0, durationSeconds: 0, restSeconds: 60),
            ExerciseSet(reps: 8, weight: 0, durationSeconds: 0, restSeconds: 60),
          ],
        ),
        WorkoutExercise(
          exercise: exercises.firstWhere((e) => e.id == 'squats'),
          sets: [
            ExerciseSet(reps: 12, weight: 0, durationSeconds: 0, restSeconds: 60),
            ExerciseSet(reps: 12, weight: 0, durationSeconds: 0, restSeconds: 60),
          ],
        ),
        WorkoutExercise(
          exercise: exercises.firstWhere((e) => e.id == 'plank'),
          sets: [
            ExerciseSet(reps: 1, weight: 0, durationSeconds: 30, restSeconds: 60),
            ExerciseSet(reps: 1, weight: 0, durationSeconds: 30, restSeconds: 60),
          ],
        ),
      ],
      difficulty: 'beginner',
      estimatedDurationMinutes: 25,
      targetMuscleGroups: ['chest', 'legs', 'core'],
      category: 'strength',
    ),
  ];
}